name: freshtrack_mobile
description: A new Flutter project for FreshTrack AI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  http: ^1.2.0
  image_picker: ^1.0.7
  
  # Optimization
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  
  # UI
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0 # Nice loading animations
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  camera: ^0.10.5+9
  camera_web: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
